# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# go to https://api.covermymeds.com/your-account/signin to get your API key and secret
# then set them as environment variables in your default shell, or put them here

development:
  secret_key_base: 8b5abc2a3db86afcc9a7406822a068768379717c37cf893a9ba414eeb7dc0120247a66a0f30dfcea46ee3ec6c6fb81a7ca8f3bc5a93b97826d621f1d0676eee4
  cmm_api_id: <%= ENV['CMM_API_KEY'] %>
  cmm_api_secret: <%= ENV['CMM_API_SECRET'] %>
  integration_cmm_api_id: <%= ENV['INTEGRATION_CMM_API_KEY'] %>
  integration_cmm_api_secret: <%= ENV['INTEGRATION_CMM_API_SECRET'] %>
  cmm_api_version: 1

test:
  secret_key_base: 8b4015cd7cb02c1477a4e690aa4290fa37cac65f5322e72d6732aa3c0412bf6d296c8fc8571665657e26165d803d3a3f589a780e3b2e3d7ea6f9892c56199810
  cmm_api_id: <%= ENV['CMM_API_KEY'] %>
  cmm_api_secret: <%= ENV['CMM_API_SECRET'] %>
  integration_cmm_api_id: <%= ENV['INTEGRATION_CMM_API_KEY'] %>
  integration_cmm_api_secret: <%= ENV['INTEGRATION_CMM_API_SECRET'] %>
  cmm_api_version: 1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  cmm_api_id: <%= ENV["CMM_API_KEY"] %>
  cmm_api_secret: <%= ENV["CMM_API_SECRET"] %>
  integration_cmm_api_id: <%= ENV['INTEGRATION_CMM_API_KEY'] %>
  integration_cmm_api_secret: <%= ENV['INTEGRATION_CMM_API_SECRET'] %>
  cmm_api_version: 1
